### ISSUE TITLE
Compiled APK?

### ISSUE THREAD

**Issue by vvzvlad** [travisgoodspeed/GoodV#1]
Could you post the assembled APK of the application or the instructions for building it?

**Comment by travisgoodspeed** [comment]
Can do.

**Comment by vvzvlad** [comment]
how do I do that?

**Comment by travisgoodspeed** [comment]
I've added build documentation to the `README.md` file in d471756.  Will close this issue once a prebuilt APK is available somewhere.

**Comment by travisgoodspeed** [comment]
The first prebuilt release is available on the Github page.  Please reopen this issue if I've signed it wrong or left any other problem with it.

https://github.com/travisgoodspeed/GoodV/releases
