### ISSUE TITLE
Every action leads to error

### ISSUE THREAD

**Issue by anonymix007** [travisgoodspeed/GoodV#7]
When trying to get info about tag, dump, erase or program I see error message: programming, read or erase error.
I'm using RF430TAL152H tag (used) and OnePlus 7 Pro. Also, NXP TagInfo says that there are some errors communicating with tag. Though I was able to read it content with proxmark3
[logcat.txt](https://github.com/travisgoodspeed/GoodV/files/5468077/logcat.txt)

**Comment by travisgoodspeed** [comment]
Please confirm that (1) you have inserted the value of `private byte[] password` in [NfcRF430TAL.java](https://github.com/travisgoodspeed/GoodV/blob/master/app/src/main/java/com/kk4vcz/goodv/NfcRF430TAL.java) and that (2) you are using an American 10 Day sensor or a non-American sensor, but not an American 14 Day sensor.

**Comment by anonymix007** [comment]
1) Oops. Could I just sniff password with proxmark3 when activating sensor with reader?
2) True. But what's wrong with American 14-day ones?

**Comment by travisgoodspeed** [comment]
1. Yes, sniff for the password or just copy and paste it from other public Libre projects.
2. American 14 Day sensors use a different protocol and run different firmware.
