### ISSUE TITLE
Not activating after erase

### ISSUE THREAD

**Issue by anonymix007** [travisgoodspeed/GoodV#8]
I was successfully at erasing tag. After that I send 02 A0 07 <password>. It returned 00DC000300538A. What does last two bytes mean and why they aren't in wiki? 
Also, is there any information on how to interpret result from A1 command?

About 8 minutes after A0 command was sent, sensor changed state from "Warming up" to "To Activate". I tried 2 different ones, and all of them had the same behavior. What does it mean? What am I doing wrong? Is it even possible to reactivate sensor after erasing it?

**Comment by anonymix007** [comment]
@travisgoodspeed Why this happens?

**Comment by hapvlz** [comment]
I think you tried to activate sensor which wasn't inside body.
As far as I seen those sensors have checks of the temperature and glucose, if they are incorrect during warm up sensor will go back to "To active" state or broken.

**Comment by anonymix007** [comment]
That's because sensor was cold, it works fine then heating it (inside yogurt making machine)
